const MAGIC = 0x53554c58
const PROTOCOL_VERSION = 1

const OP_STREAM_INPUT = 0x0001
const OP_ABORT = 0x0002
const OP_MEM_QUERY = 0x0003
const OP_SET_CONFIG = 0x0004
const OP_TOOL_RETURN = 0x0005
const OP_MEM_COMMIT = 0x0006
const OP_PING = 0x000e
const OP_SHUTDOWN = 0x000f

const OP_STREAM_CONTENT = 0x0101
const OP_STREAM_THOUGHT = 0x0102
const OP_TURN_COMPLETE = 0x0103
const OP_TOOL_CALL = 0x0104
const OP_MEM_RESPONSE = 0x0105
const OP_STATUS = 0x0106
const OP_PONG = 0x010e
const OP_ERROR = 0x01ff

const STATUS_IDLE = 0
const STATUS_ENCODING = 1
const STATUS_GENERATING = 2
const STATUS_MEMORY = 3
const STATUS_CONSOLIDATING = 4

const MODE_TEXT = 0x00
const MODE_TOKENS = 0x01

const STOP_END_OF_TURN = 0
const STOP_MAX_TOKENS = 1
const STOP_ABORTED = 2
const STOP_TOOL_CALL = 3

module.exports = {
  MAGIC,
  PROTOCOL_VERSION,
  OP_STREAM_INPUT,
  OP_ABORT,
  OP_MEM_QUERY,
  OP_SET_CONFIG,
  OP_TOOL_RETURN,
  OP_MEM_COMMIT,
  OP_PING,
  OP_SHUTDOWN,
  OP_STREAM_CONTENT,
  OP_STREAM_THOUGHT,
  OP_TURN_COMPLETE,
  OP_TOOL_CALL,
  OP_MEM_RESPONSE,
  OP_STATUS,
  OP_PONG,
  OP_ERROR,
  STATUS_IDLE,
  STATUS_ENCODING,
  STATUS_GENERATING,
  STATUS_MEMORY,
  STATUS_CONSOLIDATING,
  MODE_TEXT,
  MODE_TOKENS,
  STOP_END_OF_TURN,
  STOP_MAX_TOKENS,
  STOP_ABORTED,
  STOP_TOOL_CALL,
}
